### ISSUE TITLE
FinnhubClient.cryptoSymbols(exchange) -> properties are inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by christophermatthewsanchez** [kurtmcintire/FinnhubSwift#36]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/41021943/135187953-a7909a33-a198-4b62-9edf-9d09780da1ce.png">

**Comment by kurtmcintire** [comment]
@christophermatthewsanchez This should be fixed in Version 1.1.1. Thank you for your bug report.
